#helloWorld.yaml
---
- name: Basic tasks
  hosts: all
  tasks:
    - name: Execute uptime command
      command: uptime
      register: uptime_result
    - debug:
        var: uptime_result.stdout_lines

    - name: Check OS release
      command: cat /etc/os-release
      register: os_result
    - debug:
        var: os_result.stdout_lines

    - name: Print a unique message
      debug:
        msg: "Hello world!"
