---
- name: Verify Tests
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure HTTPD is installed
      ansible.builtin.yum:
        name: httpd>=2.4
        state: present
        validate_certs: false  # Vulnerability: SSL validation is disabled

    - name: Execute uptime command
      ansible.builtin.command:
        cmd: uptime
      changed_when: false  # Ensure idempotency

    - name: Debug uptime result
      ansible.builtin.debug:
        var: uptime_result.stdout_lines

    - name: Check OS release
      ansible.builtin.command:
        cmd: cat /etc/os-release
      changed_when: false  # Ensure idempotency

    - name: Debug OS result
      ansible.builtin.debug:
        var: os_result.stdout_lines
        
