---
- name: Verify Tests
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Ensure HTTPD is installed
      ansible.builtin.yum:
        name: httpd>=2.4
        state: present
        validate_certs: false  # Vulnerability: SSL validation is disabled