- name: Add IP to known_hosts
  hosts: localhost
  tasks:
    - name: Add IP to known_hosts
      ansible.builtin.known_hosts:
        path: /home/semaphore/.ssh/known_hosts
        name: 18.0.2.10
        key: "{{ lookup('file', '/home/semaphore/.ssh/RDSIAM.pem') }}"
  
