name: "ANSIBLE CHECKOV PIPELINE"

on:
  push:
    paths:
      - 'playbooks/**'  # Trigger only on changes in the playbooks folder
  pull_request:
    paths:
      - 'playbooks/**'  # Trigger only on changes in the playbooks folder
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  security-events: write

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository and Branch
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v1.0.3
        with:
          path: "playbooks/vulnerable/"  # <-- only one value is allowed

  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository and Branch
        uses: actions/checkout@v4

      - name: Run Checkov in silent mode
        uses: bridgecrewio/checkov-action@master
        with:
          directory: playbooks/
          framework: ansible
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Log after Checkov
        run: |
          echo "Checkov has completed"
          sleep 4
          ls -lias

      - name: Upload SARIF file to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov.sarif
